language: python
python:
  - "3.6"
# command to install dependencies
install:
- pip install codecov
# command to run tests
script:
- export DISPLAY=:0.0
- coverage run Test.py

after_success:
- codecov
